### ISSUE TITLE
Object detection cam.

### ISSUE THREAD

**Issue by shail-git** [rigvedrs/YOLO-V8-CAM#14]
I am getting similar error as https://github.com/rigvedrs/YOLO-V8-CAM/issues/8 , I dont know what is going wrong. I have rerun it multiple times. Also, I dont understand why we have to run it multiple times. For example in below it highlights everything but players and ball. I have tried using different colormaps in cv2 but the result is same.
![image](https://github.com/rigvedrs/YOLO-V8-CAM/assets/64552060/c8c42c85-62ea-4768-835b-f5feb191b357)

**Comment by bhosalems** [comment]
Yes, I am getting similar errors

**Comment by kimyd** [comment]
I have similar issue, event for the "puppies" image as follows. Ensure the model is running on the CPU, not the GPU. 

`model.cpu()` 

or 

`model = YOLO(f'yolov8n.pt').to('cpu')`

then it works fine for me. I will submit PR. 

![cam_result_puppies_od](https://github.com/user-attachments/assets/fbc138bb-d4b2-4368-befa-82d32951c5e0)

**Comment by rigvedrs** [comment]
It has been resolved in the update by @kimyd . Feel free to reopen it if it still comes up
