### ISSUE TITLE
I have added other modules in the yolov8 framework, can I generate heat maps with your repository code?

### ISSUE THREAD

**Issue by weldingCode** [rigvedrs/YOLO-V8-CAM#15]

**Comment by ComsensePersonnel1** [comment]
You can give it a try. It basically should just convert the matrix output from the layer and generate it as a heatmap.

**Comment by rigvedrs** [comment]
You can give it a try. It basically should give an output considering it will just resize the output matrix of activations from the layer into the image size, and generate the heatmap from it.
