### ISSUE TITLE
Requesting Eigen-CAM for Yolov11

### ISSUE THREAD

**Issue by snehitvaddi** [rigvedrs/YOLO-V8-CAM#25]
Hey @rigvedrs!

Your repo has been incredibly helpful for my project. With YOLOv11 gaining popularity, I was wondering if you could update it to work with YOLOv11. 

I tried running the existing code with YOLOv11 but encountered an error:
```
AttributeError: Can't get attribute 'C3k2' on <module 'ultralytics.nn.modules.block' from '/home/vaddisnehit/.local/lib/python3.12/site-packages/ultralytics/nn/modules/block.py'>
```
This was expected due to the architecture changes. Could you please modify the code to support YOLOv11 as well?

Thanks!

**Comment by rigvedrs** [comment]
@snehitvaddi You can try now. Let me know if you still come across any issue. Also, your error mostly seems related to extracting the wrong layer. There are only specific types layers EigenCam should work with

Cheers!
