### ISSUE TITLE
AssertionError in the results.py (ultralytics)

### ISSUE THREAD

**Issue by gycka** [rigvedrs/YOLO-V8-CAM#3]
I am trying to work with your YOLOv8 CAM; however, I am getting an AssertionError in BaseTensor class in the results.py line 32.

Initially, the problem originates from this line:
grayscale_cam = cam(rgb_img)[0, :, :]

It does predict the class correctly:
`224x224 golden_retriever 0.41, Labrador_retriever 0.30, Great_Pyrenees 0.09, kuvasz 0.04, cocker_spaniel 0.03, 2.4ms
Speed: 1.0ms preprocess, 2.4ms inference, 0.0ms postprocess per image at shape (1, 3, 224, 224)`

that comes from here:
`ultralytics\yolo\engine\results.py", line 32, in __init__
    assert isinstance(data, (torch.Tensor, np.ndarray))`

![info1](https://github.com/rigvedrs/YOLO-V8-CAM/assets/6606743/b6389aa6-6e41-4bdc-b93f-9ee0216be6c4)

It seems that the model does predict the classes correctly and the data in this class is a tensor/numpy array the first 3 times, but then it becomes a single digit, so it no longer is a tensor or a numpy array. This is outside of your code, but I was wondering if you have encountered anything like this before.

I also tried to convert the image to tensor as it was introduced [here](https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/EigenCAM%20for%20YOLO5.ipynb):

``` Python
transform = transforms.ToTensor()
tensor = transform(img).unsqueeze(0)
grayscale_cam = cam(tensor)[0, :, :]
```

but no success.

**Comment by rigvedrs** [comment]
Hey! Thanks for your inputs in this. It is a hacky solution indeed. I will see if there's a better way for this. Till then you can use the method you've suggested.

**Comment by rigvedrs** [comment]
This seems like an issue for the new version of ultralytics. I will try to fix it, but till then I recommend you to use ultralytics-8.0.107 or below if you want to use the package.
