### ISSUE TITLE
gradcam for yolov8-seg

### ISSUE THREAD

**Issue by yebuxiu123** [rigvedrs/YOLO-V8-CAM#5]
Thank you very much for your work, but I am now in great need of gradcam support for yolov8 instance segmention, when will this be possible please!

**Comment by enickel00** [comment]
I'm also interested if anyone's successfully implemented this for segmentation models with yolov8, or has any advice on how to get it going.

**Comment by rigvedrs** [comment]
Hey! I actually had no plans for this since I wanted to work only on Object detection and classification for my case. But I will definitely give it a try and let you know.

**Comment by Eric-Marchetti** [comment]
Hello, thank you for working on this project! I noticed that yesterday you made a commit that added support for Segmentation models and added an example to the tutorial ipynb. However when looking at the base_cam.py file that was in that commit I don't see the segmentation support. Could you please either point me to where the code is or push it to the repo? Thank you!

**Comment by rigvedrs** [comment]
It has been provided in [this notebook](https://github.com/rigvedrs/YOLO-V8-CAM/blob/main/YOLO%20v8n%20EigenCAM.ipynb )

**Comment by enickel00** [comment]
@rigvedrs  Thanks a bunch for doing that. Looking forward to trying it out.
