### ISSUE TITLE
Inquiry on Object Detection Related Error

### ISSUE THREAD

**Issue by geniecity** [rigvedrs/YOLO-V8-CAM#8]
![image](https://github.com/rigvedrs/YOLO-V8-CAM/assets/115052257/d9b84e9a-384c-4a41-9a22-74e570c73f28)

"Hello, I am trying to explain my model, which is built on yolov8 based on your model, through CAM. The issue is that while the detection of classes on the image is accurate, the heatmap is generated on parts of the image that are completely unrelated to the class. How can I resolve this issue?"

**Comment by rigvedrs** [comment]
This happens when you run the code for the first time. You will have to re-run the cells to make it provide the accurate output.

**Comment by rigvedrs** [comment]
This happens when you run the code for the first time. You will have to re-run the cells to make it provide the accurate output.

**Comment by shail-git** [comment]
I am getting similar error, I dont know what is going wrong. I have rerun it multiple times. Also, I dont understand why we have to run it multiple times. For example in below it highlights everything but players and ball. I have tried using different colormaps in cv2 but the result is same.

![image](https://github.com/rigvedrs/YOLO-V8-CAM/assets/64552060/dff8ef49-bf99-457a-9bee-44101018238e)

**Comment by kimyd** [comment]
I have similar issue, event for the "puppies" image as follows. Ensure the model is running on the CPU, not the GPU. 

`model.cpu()` 

or 

`model = YOLO(f'yolov8n.pt').to('cpu')`

then it works fine for me. I will submit PR. 

![cam_result_puppies_od](https://github.com/user-attachments/assets/fbc138bb-d4b2-4368-befa-82d32951c5e0)
